# Generated by Django 6.1 on 2026-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_sosalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='status',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
